### ISSUE TITLE
Is there any NoisyNet implementation?

### ISSUE THREAD

**Issue by forhonourlx** [cxxgtxy/deeprl-baselines#2]
Hi cxxgtxy,

Is there any NoisyNet implementation in the Rainbow baseline?
Doy you have any recommanded implementation of efficient NoisyNet?
Thank you for your help.

**Comment by cxxgtxy** [comment]
In fact, I use parameter noise from openai in place of NoisyNet .(https://arxiv.org/abs/1706.01905) since they both concern a related problem and  the former can seamlessly be implemented.
You can search the NoisyNet.

**Comment by forhonourlx** [comment]
Getting to know.
Thank you for your help.
